### ISSUE TITLE
Install in 4.0 

### ISSUE THREAD

**Issue by gustavo-etal** [trosendal/paratb#1]
Nice paper, I like to give it a go, no clear your installation is working for R 4.0

**Comment by trosendal** [comment]
Hmm, strange. The package passed checks on on R 4.0.2 on Fedora, MacOS and Windows. Can you tell me what error you are getting?

**Comment by gustavo-etal** [comment]
Centos7, I fixed at the bio, thank you for putting this together

**Comment by trosendal** [comment]
OK, I'm not sure what "fixed at the bio" means but I'm glad its working under CentOS7 for you now  :+1:
